name: Build Node

on:
  workflow_dispatch:

jobs:
  trigger-other:
    permissions:
      packages: write
      contents: read
    uses: "./.github/workflows/builder.yml"
    with:
      build_target: node
